### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by paigenorth** [YellPika/vscode-latex-input#10]
I've had latex-input installed as an extension for several years, but have had it disabled for maybe a year now. On enabling it, it doesn't seem to work anymore. For example, typing \circ in a file produces many suggestions, but none are a unicode symbol. I'm using Version: 1.75.0 on a Mac. Thanks!

**Comment by mroman42** [comment]
Same problem here. It seems to have started after an update of vscode; reverting the extension to v0.5 has not helped. 
This is under vscode1.78.1 on Ubuntu. I have not tried yet to revert vscode to a previous version.

**Comment by YellPika** [comment]
Seems to be fixed in current VSCode 1.87.2.
