### ISSUE TITLE
Does not work in Jupyter notebooks

### ISSUE THREAD

**Issue by nathancarter** [YellPika/vscode-latex-input#5]
VS Code has excellent support for Jupyter notebooks, but this extension does not work presently in their code cells.  It would be great if it did, so that we can use Greek letter variable names in statistical code (e.g., `\mu` for population mean, `\sigma` for standard deviation, `\delta x`, etc.).

Steps to reproduce:

 * Open an `.ipynb` file in VS Code, which should suggest using the built-in Jupyter editor (or extension?).
 * Say yes.
 * Try to edit a code cell and use `\mu` for example.

**Comment by mapio** [comment]
This seems to fix it https://github.com/microsoft/vscode-jupyter/issues/9363#issuecomment-1272241667

**Comment by YellPika** [comment]
Fixed by 4c04475ddd877ed94119d67b2cfa3d200d113642.
