### ISSUE TITLE
Cannot find module 'vscode-latex-input/out/extension'

### ISSUE THREAD

**Issue by BrianKo14** [YellPika/vscode-latex-input#7]
I'm trying to test the extension using the configuration in VSCode, but I get the following error:

```
Activating extension 'yellpika.latex-input' failed: Cannot find module '.../vscode-latex-input/out/extension'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.
```

I can see the published project folder has an `out/extension.js` directory which this GitHub repo doesn't have. How exactly do you test your extension?

I could really use your code for a personal project of mine, I would be incredibly thankful if you could help me out with this one!

**Comment by YellPika** [comment]
This is two years late, but in case someone else comes upon this...

You need to compile the project (which is written in TypeScript) in order to obtain the `out/extension.js` directory.

```bash
# From root directory of project
npm install # Will probably fail, but that shouldn't cause problems
npm run compile
```
